spring.profiles.active: dev

line:
  bot:
    handler:
      enabled: true
spring:
  thymeleaf:
    prefix: 'file:src/main/resources/templates/'
    suffix: '.html'
    cache: false
  resources:
    static-locations: 'file:src/main/resources/static/'

server:
  port: 8080
  tomcat.max-threads: 32

spring.devtools.restart:
  additional-paths: /src/main/resources/templates
  additional-exclude: '**' # Restart is not needed. Only reload needed.
  quiet-period: 50
  poll-interval: 100


---
spring.profiles: prod

line.bot:
  channel-secret: 639b48d5a333f63d9e8daba0f92e069d
  channel-token: yxz7nrcYz9b8f0NSWNrN1lBlgblEkLtIohoUrdGYkFN5pCYwEFC92xBEcfAOiE0B6L15Ri4N12GD3/d/jQS60GJZLX+eOnzVrqY8lpBFOtBvNvNJV6Pngw/rc3KTh0ckdd7VrR7LE9hMI6OdtfCZTgdB04t89/1O/w1cDnyilFU=

host: https://groupmap.link/
host-internal: http://localhost:${server.port}/
line-id: @zzk9691a

spring:
  mongodb:
    embedded:
      storage:
        database-dir: /var/groupmap

---
spring.profiles: dev

line.bot:
  channel-secret: f68e50298db7e80e919fcd3190750891
  channel-token: msT856rFni14xlgxampMiSFZ0bV+cyRLjlgsPaKISDqajfI+LM5UC/QddKi4huKA+nKMtyzsxo56/V0ALCZkxL+ZmsBneFWMUvrdqnT8rof+upFaB8e91M6z5lFoTiHZvzfyWH/RVXMrhIcU2OY1ngdB04t89/1O/w1cDnyilFU=

host: 'https://bc2da3e6.ngrok.io'
host-internal: http://localhost:${server.port}/
line-id: @ndg3530x

spring:
  mongodb:
    embedded:
      storage:
        database-dir: /Users/jp20217/groupMap

#
#server:
#  ssl:
#    enabled: true
#    enabled-protocols: TLSv1.2
#    key-store: classpath:kazuki-ma.serendipity.la.keystore
#    key-store-password: tetlist
#  port: 8443



