spring.profiles.active: dev

line:
  bot:
    handler:
      enabled: true
spring:
  thymeleaf:
    prefix: 'file:src/main/resources/templates/'
    suffix: '.html'
    cache: false
  resources:
    static-locations: 'file:src/main/resources/static/'

server.port: 8080


spring.devtools.restart:
  additional-paths: /src/main/resources/templates
  additional-exclude: '**' # Restart is not needed. Only reload needed.
  quiet-period: 50
  poll-interval: 100


---
spring.profiles: prod

line.bot:
  channel-secret: 22a1d9fd8862d75a9973ed19e29b002d
  channel-token: CeBEJ0d3PV86Ml8l/WIsNa8P14jG+1McKdPg09CH9cRii+/8fzrWDGuWtrQ27R7rdOLTqp01/bEeH9CIzBrCExbzaJ+gFJm878DCBNjzUDeIQIAgWNdqfquOEHUA24CY2sy7vmm+fmi8k6TxANY8hwdB04t89/1O/w1cDnyilFU=

host: https://groupmap.link/
host-internal: https://groupmap.link/
spring:
  mongodb:
    embedded:
      storage:
        database-dir: /var/groupmap

---
spring.profiles: dev

line.bot:
  channel-secret: f68e50298db7e80e919fcd3190750891
  channel-token: msT856rFni14xlgxampMiSFZ0bV+cyRLjlgsPaKISDqajfI+LM5UC/QddKi4huKA+nKMtyzsxo56/V0ALCZkxL+ZmsBneFWMUvrdqnT8rof+upFaB8e91M6z5lFoTiHZvzfyWH/RVXMrhIcU2OY1ngdB04t89/1O/w1cDnyilFU=

host: 'https://8bf2580c.ngrok.io/'
host-internal: http://localhost:${server.port}/
spring:
  mongodb:
    embedded:
      storage:
        database-dir: /Users/jp20217/groupMap

#
#server:
#  ssl:
#    enabled: true
#    enabled-protocols: TLSv1.2
#    key-store: classpath:kazuki-ma.serendipity.la.keystore
#    key-store-password: tetlist
#  port: 8443



