# Definition of GitHub Actions.
# Designed to working both line's and forked repository.
#
# Note:
#  Set -xmx6g due to VM Spec = 2core, 7G RAM.
name: CI
on: [push, pull_request]
jobs:
  test:
    name: test (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java: [ '1.8', '11.x' ] # LTS's. (As of 2019-10, Gradle don't support JDK 13.)
    steps:
    - name: actions/setup-java@v1 (JDK ${{ matrix.java }})
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - uses: actions/checkout@v1
    - run: |
        mkdir -p ~/.gradle
        echo "org.gradle.jvmargs=-Xms6g -Xmx6g" >> ~/.gradle/gradle.properties
        echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
    - run: ./gradlew -v
    - run: ./gradlew check -xcheckstyleMain -xcheckstyleTest -xspotbugsMain -xspotbugsTest
    # Runs all check and its dependency exept which runs on splitted jobs.

  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: actions/setup-java@v1 (JDK 1.8)
      uses: actions/setup-java@v1
      with:
        java-version: 8
        architecture: x64
    - uses: actions/checkout@v1
    - run: |
        mkdir -p ~/.gradle
        echo "org.gradle.jvmargs=-Xms6g -Xmx6g" >> ~/.gradle/gradle.properties
        echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
    - run: ./gradlew -v
    - run: ./gradlew checkstyleMain checkstyleTest --parallel

  spotbugs:
    name: spotbugs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: actions/setup-java@v1 (JDK 1.8)
      uses: actions/setup-java@v1
      with:
        java-version: 8
        architecture: x64
    - uses: actions/checkout@v1
    - run: |
        mkdir -p ~/.gradle
        echo "org.gradle.jvmargs=-Xms6g -Xmx6g" >> ~/.gradle/gradle.properties
        echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
    - run: ./gradlew -v
    - run: ./gradlew spotbugsMain spotbugsTest --parallel

  codeCoverageReport:
    name: codeCoverageReport
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: actions/setup-java@v1 (JDK 1.8)
      uses: actions/setup-java@v1
      with:
        java-version: 8
        architecture: x64
    - uses: actions/checkout@v1
    - run: |
        mkdir -p ~/.gradle
        echo "org.gradle.jvmargs=-Xms6g -Xmx6g" >> ~/.gradle/gradle.properties
        echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
    - run: ./gradlew -v
    - run: ./gradlew test codeCoverageReport
    - run: |
        bash <(curl -s https://codecov.io/bash) -f ./line-bot-api-client/build/jacoco/report.xml -F line_bot_api_client
        bash <(curl -s https://codecov.io/bash) -f ./line-bot-model/build/jacoco/report.xml -F line_bot_model
        bash <(curl -s https://codecov.io/bash) -f ./line-bot-spring-boot/build/jacoco/report.xml -F line_bot_spring_boot
        bash <(curl -s https://codecov.io/bash) -f ./line-bot-cli/build/jacoco/report.xml -F line_bot_cli
        bash <(curl -s https://codecov.io/bash) -f ./line-bot-servlet/build/jacoco/report.xml -F line_bot_servlet
